valgrind-gcc:
  image: ubuntu:yakkety
  script: ./build/ci/gitlab valgrind-gcc
  only:
    - master
    - stable
    - oldstable

valgrind-clang:
  image: ubuntu:yakkety
  script: ./build/ci/gitlab valgrind-clang
  only:
    - master
    - stable
    - oldstable
