language: cpp
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y --force-yes gcc-4.8 g++-4.8
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
  - sudo apt-get install tor
install: autoreconf -i
script: ./configure && make -j2 V=0 && make -j2 check-am V=0
compiler:
  - clang
  - g++
